language : java

script : mvn clean install

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

jdk:
  - oraclejdk8

branches :
   only :
     - master
notifications :
   email :
     - maxwunj@gmail.com
