language : java

script : mvn cobertura:cobertura
#mvn clean install

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

jdk:
  - oraclejdk8

addons:
  firefox: "latest-nightly"

branches :
   only :
     - master

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications :
   email :
     - maxwunj@gmail.com
